"""add_source_url_to_pdfs

Revision ID: 561e83556c19
Revises: d86b6c04e0a9
Create Date: 2026-03-23 04:07:35.040946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561e83556c19'
down_revision: Union[str, Sequence[str], None] = 'd86b6c04e0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('source_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdfs', 'source_url')
    # ### end Alembic commands ###
