"""fix_shares_model_phase6

Revision ID: f909f7eeb9e6
Revises: ba0db7f2ac83
Create Date: 2026-03-08 13:05:18.768496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f909f7eeb9e6'
down_revision: Union[str, Sequence[str], None] = 'ba0db7f2ac83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('annotation_set_id', sa.UUID(), nullable=False))
    op.add_column('shares', sa.Column('shared_with', sa.UUID(), nullable=True))
    op.add_column('shares', sa.Column('share_token', sa.String(length=64), nullable=False))
    op.add_column('shares', sa.Column('permission', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('shares_token_key'), 'shares', type_='unique')
    op.create_unique_constraint(None, 'shares', ['share_token'])
    op.drop_constraint(op.f('shares_pdf_id_fkey'), 'shares', type_='foreignkey')
    op.create_foreign_key(None, 'shares', 'annotation_sets', ['annotation_set_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shares', 'users', ['shared_with'], ['id'], ondelete='CASCADE')
    op.drop_column('shares', 'expires_at')
    op.drop_column('shares', 'token')
    op.drop_column('shares', 'pdf_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('pdf_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('shares', sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('shares', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.create_foreign_key(op.f('shares_pdf_id_fkey'), 'shares', 'pdfs', ['pdf_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'shares', type_='unique')
    op.create_unique_constraint(op.f('shares_token_key'), 'shares', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('shares', 'permission')
    op.drop_column('shares', 'share_token')
    op.drop_column('shares', 'shared_with')
    op.drop_column('shares', 'annotation_set_id')
    # ### end Alembic commands ###
